2016-02-23 18:18:17,928 : INFO  : [uit.ent.synchronizer.table.Cursus_v2] 
Logging initialized.
2016-02-23 18:18:17,929 : ERROR : [uit.ent.synchronizer.table.Cursus_v2] 
Error while Synchronizing uit.ent.synchronizer.table.Cursus_v2
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'rng_elp' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2543)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2022)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1940)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1925)
	at uit.ent.synchronizer.table.Cursus_v2.syncIndividu(Cursus_v2.java:183)
	at uit.ent.synchronizer.table.Cursus_v2.synchronize(Cursus_v2.java:42)
	at uit.ent.synchronizer.table.Individu.synchronize(Individu.java:311)
	at uit.ent.synchronizer.table.Synchronisation.run(Synchronisation.java:71)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:30)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-02-23 18:51:34,129 : INFO  : [uit.ent.synchronizer.table.RemoveExpiredSynchronisationData] 
Logging initialized.
2016-02-23 18:51:34,130 : ERROR : [uit.ent.synchronizer.table.RemoveExpiredSynchronisationData] 
Erreur lors de la suppression des données de synchronisation %n
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ent.cursusannee' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2543)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:998)
	at uit.ent.synchronizer.table.RemoveExpiredSynchronisationData.run(RemoveExpiredSynchronisationData.java:49)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:44)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-02-25 15:57:34,355 : INFO  : [uit.ent.synchronizer.table.CursusAnnee] 
Logging initialized.
2016-02-25 15:57:34,358 : ERROR : [uit.ent.synchronizer.table.CursusAnnee] 
Error while Synchronizing uit.ent.synchronizer.table.CursusAnnee
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ent.cursusannee' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2543)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2022)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1940)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1925)
	at uit.ent.synchronizer.table.CursusAnnee.syncIndividu(CursusAnnee.java:164)
	at uit.ent.synchronizer.table.CursusAnnee.synchronize(CursusAnnee.java:29)
	at uit.ent.synchronizer.table.Individu.synchronize(Individu.java:297)
	at uit.ent.synchronizer.table.Synchronisation.run(Synchronisation.java:71)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:30)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-03-02 16:04:30,474 : INFO  : [uit.ent.synchronizer.table.CursusAnnee] 
Logging initialized.
2016-03-02 16:04:30,476 : ERROR : [uit.ent.synchronizer.table.CursusAnnee] 
Error while Synchronizing uit.ent.synchronizer.table.CursusAnnee
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'COD_GPE_IAG' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2543)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2022)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1940)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1925)
	at uit.ent.synchronizer.table.CursusAnnee.syncIndividu(CursusAnnee.java:164)
	at uit.ent.synchronizer.table.CursusAnnee.synchronize(CursusAnnee.java:29)
	at uit.ent.synchronizer.table.Individu.synchronize(Individu.java:296)
	at uit.ent.synchronizer.table.Synchronisation.run(Synchronisation.java:71)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:30)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-03-03 15:42:02,480 : INFO  : [uit.ent.synchronizer.table.Cursus_v2] 
Logging initialized.
2016-03-03 15:42:02,481 : ERROR : [uit.ent.synchronizer.table.Cursus_v2] 
Error while Synchronizing uit.ent.synchronizer.table.Cursus_v2
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ent.cursusresultat_v2' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2543)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2022)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1940)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1925)
	at uit.ent.synchronizer.table.Cursus_v2.syncIndividu(Cursus_v2.java:183)
	at uit.ent.synchronizer.table.Cursus_v2.synchronize(Cursus_v2.java:42)
	at uit.ent.synchronizer.table.Individu.synchronize(Individu.java:310)
	at uit.ent.synchronizer.table.Synchronisation.run(Synchronisation.java:71)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:30)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
