2016-02-17 15:07:38,449 : INFO  : [uit.ent.synchronizer.quartz.Execution] 
Logging initialized.
2016-02-17 15:07:38,450 : ERROR : [uit.ent.synchronizer.quartz.Execution] 
Update datesync
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1113)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4038)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4004)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:36)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-02-17 15:09:43,465 : INFO  : [uit.ent.synchronizer.quartz.Execution] 
Logging initialized.
2016-02-17 15:09:43,466 : ERROR : [uit.ent.synchronizer.quartz.Execution] 
Update datesync
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1113)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4038)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4004)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:36)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-02-17 15:22:20,380 : INFO  : [uit.ent.synchronizer.quartz.Execution] 
Logging initialized.
2016-02-17 15:22:20,381 : ERROR : [uit.ent.synchronizer.quartz.Execution] 
Update datesync
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1113)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4038)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4004)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:36)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-02-17 15:25:25,437 : INFO  : [uit.ent.synchronizer.quartz.Execution] 
Logging initialized.
2016-02-17 15:25:25,438 : ERROR : [uit.ent.synchronizer.quartz.Execution] 
Update datesync
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1113)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4038)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4004)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:36)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
2016-02-17 15:25:48,113 : ERROR : [uit.ent.synchronizer.quartz.Execution] 
Erreur lors de la suppression des données de synchronisation
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ent.cursusresultat' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3308)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1837)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1961)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2543)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1737)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:998)
	at uit.ent.synchronizer.table.RemoveExpiredSynchronisationData.run(RemoveExpiredSynchronisationData.java:46)
	at uit.ent.synchronizer.quartz.Execution.execute(Execution.java:44)
	at uit.ent.synchronizer.test.Test.main(Test.java:13)
